### ISSUE TITLE
Finetuning provided model

### ISSUE THREAD

**Issue by icoric4** [TencentARC/GFPGAN#44]
Hello and thanks for an awesome project!

I am trying to finetune this model -  https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth , but when I have   
network_g:
     type: GFPGANv1
I get a lot of mismatches between the layers. So I figured the models are different.

Am I right to assume that this ckpt is the GFPGANv1Clean model and if so, how can I finetune it. 

When I change the config to:
network_g:
     type: GFPGANv1Clean
I get: 
KeyError: "No object named 'GFPGANv1Clean' found in 'arch' registry!"

**Comment by xinntao** [comment]
@icoric4  Finetuning the https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth has not been supported yet. As this model is converted from another model  (which is not released.)

I will add the model, but it may take much time ~

**Comment by icoric4** [comment]
Thanks!

**Comment by icoric4** [comment]
Hello, I have another question. 

When training from scratch a model like this one https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth, 

could you share the training settings you have used to train it, similar to this?  


```
# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-3
  optim_d:
    type: Adam
    lr: !!float 2e-3
  optim_component:
    type: Adam
    lr: !!float 2e-3

  scheduler:
    type: MultiStepLR
    milestones: [600000, 700000]
    gamma: 0.5

  total_iter: 800000
  warmup_iter: -1  # no warm up

  # losses
  # pixel loss
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-1
    reduction: mean
  # L1 loss used in pyramid loss, component style loss and identity loss
  L1_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

  # image pyramid loss
  pyramid_loss_weight: 1
  remove_pyramid_loss: 50000
  # perceptual loss (content and style losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1
    style_weight: 50
    range_norm: true
    criterion: l1
  # gan loss
  gan_opt:
    type: GANLoss
    gan_type: wgan_softplus
    loss_weight: !!float 1e-1
  # r1 regularization for discriminator
  r1_reg_weight: 10
  # facial component loss
  gan_component_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1
  comp_style_weight: 200
  # identity loss
  identity_weight: 10

  net_d_iters: 1
  net_d_init_iters: 0
  net_d_reg_every: 16

```
