### ISSUE TITLE
problem that enhancement without colorizationn

### ISSUE THREAD

**Issue by TracelessLe** [TencentARC/GFPGAN#98]
> If you do not want to have any color enhancement, you may set `color_jitter_shift: ~`

Hi @xinntao @syfbme,  I have set "color_jitter_prob: ~" and retrain, but the restore results of gray images are still with colorization. Would you please give some advice.

![image](https://user-images.githubusercontent.com/22371026/141266374-144c293e-f533-4aac-bcd6-cf0744bbc7bd.png)

The config of dataset is listed below:

```
# dataset and data loader settings
datasets:
  train:
    name: FFHQ
    type: FFHQDegradationDataset
    dataroot_gt: ../../dataset/ffhq
    io_backend:
      # type: lmdb
      type: disk

    use_hflip: true
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    out_size: 256

    blur_kernel_size: 41
    kernel_list: ['iso', 'aniso']
    kernel_prob: [0.5, 0.5]
    blur_sigma: [0.1, 10]
    downsample_range: [0.8, 8]
    noise_range: [0, 20]
    jpeg_range: [60, 100]

    # color jitter and gray
    #color_jitter_prob: 0.3
    #color_jitter_shift: 20
    #color_jitter_pt_prob: 0.3
    #gray_prob: 0.01

    # If you do not want colorization, please set
    color_jitter_prob: ~
    color_jitter_shift: 0
    color_jitter_pt_prob: ~
    gray_prob: 0.05
    gt_gray: True

    crop_components: true
    component_path: experiments/pretrained_models/FFHQ_eye_mouth_landmarks_256.pth
    # eye_enlarge_ratio: 1.4

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
```

_Originally posted by @TracelessLe in https://github.com/TencentARC/GFPGAN/issues/11#issuecomment-966100513_
